// tests/schema-audit-load-agreement-oracle.test.mjs — BLZ-407.
//
// THE PRODUCT ASSERTION: `blaze audit`'s `ok` and the load path's refusal agree, for every
// schema-override shape. Before this ticket they did not — a board whose `blaze.config.json`
// carried `{"schema": {"types": {"spike": 7}}}` made `blaze audit` report `ok=true` while
// every non-exempt verb refused with `SchemaOverrideError`, the SAME message, because
// `auditCorpus` read `validateSchema`'s flattened strings and filed every problem under one
// soft kind — the severity tag `collectSchemaProblems` already carries was thrown away.
//
// GROUND TRUTH IS `assertSchemaValid`, NOT THE AUDIT. Every case below runs the real load-path
// mechanism (mirroring `scripts/cli.mjs`'s preflight exactly: the top layer, then each project
// layer, refuse if either throws) and compares its actual throw/no-throw against `auditCorpus`'s
// actual `ok`. Neither side is derived from the other, and neither is computed from a hardcoded
// list of "these shapes are hard" — that is the vacuity trap a run of five wrong severities in a
// row on a sibling ticket fell into, each round pinning only the case that made its round's
// claim true.
//
// THE CROSS-PRODUCT is generated by nested loops over ONE list of override shapes, applied to
// BOTH layers (`blaze.config.json`'s `schema` and a `project.json`'s `schema`) — not a
// hand-written table of (config, project) pairs. The shape list itself is read off
// `collectSchemaProblems` (scripts/model/schema-config.mjs): one entry per `hard(...)` call
// site, one per `soft(...)` call site, and the well-formed controls.
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { auditCorpus } from "../scripts/model/audit.mjs";
import { resolveSchema, assertSchemaValid, validateSchema, collectSchemaProblems }
  from "../scripts/model/schema-config.mjs";

// --- the override shapes, one per branch of collectSchemaProblems ----------------------------
// Each entry is `[name, value]`, where `value` is what would sit at `schema` in either
// blaze.config.json or project.json. `undefined` means the block is absent — a layer's own
// well-formed control. A shape is applied identically at either layer; which branch it
// exercises where is NOT hand-predicted here (some are layer-specific, e.g. a per-project
// `linkTypes` block is inert only at the project layer) — the oracle asks the real functions,
// not this list, what a given placement produces.

// One custom type ("spike") and one custom workflow ("tiny") isolate every shape from the
// engine's own defaults, so a shape only ever changes what it names.
const HARD_SHAPES = [
  ["type: not an object", { types: { spike: 7 } }],
  ["type: bad level", { types: { spike: { level: "0", workflow: "delivery", parentTypes: [], required: [] } } }],
  ["type: workflow not a name", { types: { spike: { level: 0, workflow: 7, parentTypes: [], required: [] } } }],
  ["type: workflow names an undeclared workflow", { types: { spike: { level: 0, workflow: "ghost", parentTypes: [], required: [] } } }],
  ["type: parentTypes not an array", { types: { spike: { level: 0, workflow: "delivery", parentTypes: "x", required: [] } } }],
  ["type: parentTypes names an undeclared type", { types: { spike: { level: 0, workflow: "delivery", parentTypes: ["nope"], required: [] } } }],
  ["type: required not an array", { types: { spike: { level: 0, workflow: "delivery", parentTypes: [], required: "x" } } }],
  ["type: required entry not a field name", { types: { spike: { level: 0, workflow: "delivery", parentTypes: [], required: ["title", 3] } } }],
  ["workflow: not an object", { workflows: { tiny: 7 } }],
  ["workflow: statuses not a non-empty array", { workflows: { tiny: { statuses: [], terminal: [], transitions: [], resolutionOnTerminal: {} } } }],
  ["workflow: missing terminal", { workflows: { tiny: { statuses: ["a", "b"], transitions: [["a", "b"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: terminal not an array", { workflows: { tiny: { statuses: ["a", "b"], terminal: "b", transitions: [["a", "b"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a terminal not among its statuses", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["c"], transitions: [["a", "b"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: missing transitions", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: transitions not an array", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: "x", resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a transition not a [from,to] pair", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a transition names an unknown status", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "c"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a bad reopenTo", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], reopenTo: "c", resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: missing resolutionOnTerminal", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]] } } }],
  ["workflow: resolutionOnTerminal not an object", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], resolutionOnTerminal: "x" } } }],
  ["workflow: a resolution on an unknown status", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], resolutionOnTerminal: { a: "done" } } } }],
  ["workflow: a non-resolution value", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], resolutionOnTerminal: { b: "bogus" } } } }],
  ["types container is the wrong shape (BLZ-396)", { types: "notanobject" }],
  ["workflows container is the wrong shape (BLZ-396)", { workflows: 42 }],
  ["whole schema is a string", "a string"],
  ["whole schema is an array", ["x"]],
];

// BLZ-414 round 2. THE THIRD ELEMENT IS THE SHAPE'S OWN BRANCH, and it is load-bearing.
//
// The coverage test used to assert only `problems.some((p) => !p.hard)` — ANY soft
// problem — and review measured what that is worth: deleting BOTH soft link-type
// branches from `scripts/model/schema-config.mjs` left `soft shape reaches a soft
// branch: a link type naming an undeclared endpoint kind (BLZ-392)` GREEN, satisfied by
// the co-occurring "per-project linkTypes block is inert" problem that a `linkTypes`
// shape raises at the project layer whatever else it says. Two of the four shapes here
// carry that passenger, so for them the old assertion could never fail.
//
// Each shape now names the message its OWN `soft(...)` call site emits, so "this shape
// reaches its branch" is what is actually checked — which is what the describe below
// has always claimed.
const SOFT_SHAPES = [
  ["an inert per-project linkTypes block", { linkTypes: { Precedes: { source_kinds: ["task"], target_kinds: ["task"] } } },
    /schema\.linkTypes does not reach the scheduler/],
  ["a malformed top-level schema.linkTypes entry", { linkTypes: { Precedes: { source_kinds: "nope", target_kinds: [] } } },
    /schema\.linkTypes\["Precedes"\]\.source_kinds must be an array of type names, got string/],
  // BLZ-414. The header claims one shape per soft call site; two link-type sites had
  // none. This is the reachable one: a WELL-FORMED override entry (so `mergeLinkTypes`
  // keeps it) whose endpoint names a type that is not declared — the BLZ-392 typo that
  // leaves a type silently unschedulable. Without it, `collectSchemaProblems`'s
  // "names ... which is not a declared type" branch was never executed by this oracle at
  // either layer. The other site is unreachable through the config layering and is
  // pinned separately, by name, at the foot of this file.
  ["a link type naming an undeclared endpoint kind (BLZ-392)",
    { linkTypes: { Precedes: { source_kinds: ["ghost"], target_kinds: ["task"] } },
    }, /link type "Precedes" names "ghost" in source_kinds, which is not a declared type/],
  ["a deliberately narrowed requirement workflow (BLZ-361)", { workflows: { requirement: {
    statuses: ["proposed", "implemented", "rejected", "obsolete"],
    terminal: ["implemented", "rejected", "obsolete"],
    transitions: [["proposed", "implemented"], ["proposed", "rejected"], ["proposed", "obsolete"],
                  ["implemented", "obsolete"]],
    reopenTo: "proposed",
    resolutionOnTerminal: { implemented: "done", rejected: "wont-do", obsolete: "wont-do" },
  } } }, /workflow "requirement" omits "verified", which the goal:achieved gate requires/],
];

const CONTROL_SHAPES = [
  ["absent — no schema block at all", undefined],
  ["well-formed custom type", { types: { spike: { level: 0, workflow: "delivery", parentTypes: [], required: [] } } }],
];

const SHAPES = [...HARD_SHAPES, ...SOFT_SHAPES, ...CONTROL_SHAPES];

// --- ground truth and the mechanism under test ------------------------------------------------

const buildConfig = (v) => (v === undefined ? {} : { schema: v });
const buildProject = (v) => (v === undefined ? { key: "P" } : { key: "P", schema: v });

/** Mirrors scripts/cli.mjs's preflight EXACTLY: the top layer, then each project layer, and
 *  refuse the moment either throws. This — NOT a prediction — is ground truth. */
function loadPathRefuses(config, project) {
  const top = resolveSchema({ config });
  try { assertSchemaValid({ ...top, config }); }
  catch { return true; }
  const resolved = { ...resolveSchema({ config, project }), linkTypes: top.linkTypes };
  try { assertSchemaValid({ ...resolved, config, project }); }
  catch { return true; }
  return false;
}

// BLZ-416: a PROJECT-layer problem is attributed to its project in the finding's own detail
// text — the top layer is not, because that block belongs to no one project. The fixture's
// only project key is "P". Written out here as a literal rather than imported from
// `scripts/model/audit.mjs`, because an oracle that reads the subject under test for its
// ground truth is exactly what BLZ-423 and BLZ-431 exist to forbid.
const attributed = (message) => (message.startsWith("project.json:")
  ? `projects/P/${message}`
  : `projects/P: ${message}`);

/** What `auditCorpus` SHOULD produce for the schema layer, computed independently of it: the
 *  same top-then-project walk with cross-layer dedup by message, but built here from
 *  `collectSchemaProblems` directly rather than by calling `auditCorpus` and trusting its own
 *  bookkeeping. Returns the hard/soft partition of every DISTINCT message. */
function expectedPartition(config, project) {
  const topResolved = resolveSchema({ config });
  const endpointTypes = { ...topResolved.types, ...resolveSchema({ config, project }).types };
  const topProblems = collectSchemaProblems({ ...topResolved, config, endpointTypes });
  const topByMsg = new Map();
  for (const p of topProblems) if (!topByMsg.has(p.message)) topByMsg.set(p.message, p.hard);
  const resolved = { ...resolveSchema({ config, project }), linkTypes: topResolved.linkTypes };
  const projProblems = collectSchemaProblems({ ...resolved, config, project, endpointTypes })
    .filter((p) => !topByMsg.has(p.message));
  const hard = new Set(), soft = new Set();
  for (const [msg, isHard] of topByMsg) (isHard ? hard : soft).add(msg);
  for (const p of projProblems) (p.hard ? hard : soft).add(attributed(p.message));
  return { hard, soft };
}

/** The union `validateSchema` itself would report for the same two layers, deduped the same
 *  way — the independent reference for "no problem lost or duplicated" (validateSchema is the
 *  long-established, separately-tested reporting path; this does not call collectSchemaProblems
 *  at all). */
function expectedDetailSetViaValidateSchema(config, project) {
  const topResolved = resolveSchema({ config });
  const endpointTypes = { ...topResolved.types, ...resolveSchema({ config, project }).types };
  const topMsgs = validateSchema({ ...topResolved, config, endpointTypes });
  const topSet = new Set(topMsgs);
  const resolved = { ...resolveSchema({ config, project }), linkTypes: topResolved.linkTypes };
  const projMsgs = validateSchema({ ...resolved, config, project, endpointTypes })
    .filter((m) => !topSet.has(m))
    .map(attributed);
  return new Set([...topSet, ...projMsgs]);
}

const oneGoalTicket = { frontmatter: { id: "P-1", type: "goal", components: [], labels: [], links: [] }, body: "x" };

const sorted = (s) => [...s].sort();

describe("BLZ-407 oracle: blaze audit's ok agrees with the load path's refusal, for every schema-override shape", () => {
  let cases = 0;
  let clauses = 0;
  const check = (cond, msg) => { clauses++; assert.ok(cond, msg); };
  const sameSet = (actual, expected, msg) => { clauses++; assert.deepEqual(sorted(actual), sorted(expected), msg); };

  for (const [configName, configValue] of SHAPES) {
    for (const [projectName, projectValue] of SHAPES) {
      cases++;
      test(`config=[${configName}] x project=[${projectName}]`, () => {
        const config = buildConfig(configValue);
        const project = buildProject(projectValue);

        const refused = loadPathRefuses(config, project);
        const audit = auditCorpus({ tickets: [oneGoalTicket], projects: { P: project }, config });

        // --- the ok/refusal agreement, both directions ----------------------------------
        check(!(refused && audit.ok),
          `assertSchemaValid throws for config=[${configName}] project=[${projectName}] `
          + `but audit.ok is still true`);
        check(!(!refused && !audit.ok),
          `assertSchemaValid does not throw for config=[${configName}] project=[${projectName}] `
          + `but audit.ok is false — the mirror-image over-refusal`);

        // --- the finding-level claim: no problem lost, duplicated, or under the wrong kind ---
        const actualHard = new Set(audit.findings
          .filter((f) => f.kind === "schema-malformed").map((f) => f.detail));
        const actualSoft = new Set(audit.findings
          .filter((f) => f.kind === "schema-invalid").map((f) => f.detail));
        const expected = expectedPartition(config, project);
        sameSet(actualHard, expected.hard,
          `schema-malformed details differ from collectSchemaProblems's hard partition `
          + `for config=[${configName}] project=[${projectName}]`);
        sameSet(actualSoft, expected.soft,
          `schema-invalid details differ from collectSchemaProblems's soft partition `
          + `for config=[${configName}] project=[${projectName}]`);
        check([...actualHard].every((m) => !actualSoft.has(m)),
          `a message is filed under BOTH schema-malformed and schema-invalid for `
          + `config=[${configName}] project=[${projectName}]`);

        // --- the union equals validateSchema's own output, as a set (independent reference) ---
        const union = new Set([...actualHard, ...actualSoft]);
        sameSet(union, expectedDetailSetViaValidateSchema(config, project),
          `schema-malformed ∪ schema-invalid details differ from validateSchema's output `
          + `for config=[${configName}] project=[${projectName}]`);
      });
    }
  }

  // BLZ-415. Six clauses per case is a property of the loop body's SHAPE, not a figure
  // read off a passing run: 2 ok-agreement directions, 2 partition-set comparisons, 1
  // no-overlap check, 1 union-vs-validateSchema comparison. Count them in the source
  // above, not in a console line.
  const CLAUSES_PER_CASE = 6;

  test("the oracle's own scale — ASSERTED, not merely printed (BLZ-415)", () => {
    // The dimension sizes first. `cases === SHAPES.length ** 2` alone is self-referential
    // — deleting a shape shrinks both sides of it — so the shape lists' own lengths are
    // pinned, one entry per branch of `collectSchemaProblems` plus the two controls.
    assert.equal(HARD_SHAPES.length, 26, "the hard-shape dimension changed size");
    assert.equal(SOFT_SHAPES.length, 4, "the soft-shape dimension changed size");
    assert.equal(CONTROL_SHAPES.length, 2, "the control dimension changed size");
    assert.equal(SHAPES.length, 32, "the shape list is not the three dimensions concatenated");

    const expectedCases = SHAPES.length * SHAPES.length;
    assert.equal(cases, expectedCases,
      `expected ${SHAPES.length} shapes squared; the loop above enumerated something else`);
    // BLZ-415: the count is ASSERTED. Before this ticket it was only PRINTED, so
    // deleting one of the six clauses from the loop body dropped 961 assertions and the
    // file still reported 962/962 pass — the evidence shrank in silence.
    assert.equal(clauses, expectedCases * CLAUSES_PER_CASE,
      `the oracle executed ${clauses} clauses; ${expectedCases} cases x ${CLAUSES_PER_CASE} `
      + "clauses per case is what the loop body above contains. A clause was added or "
      + "removed — change CLAUSES_PER_CASE deliberately rather than letting the oracle shrink");
    console.log(`BLZ-407 oracle: ${cases} cases (${SHAPES.length} shapes squared), `
      + `${clauses} clauses asserted (${CLAUSES_PER_CASE} per case)`);
  });
});

// =============================================================================
// BLZ-414 — the header's "one shape per hard/soft call site" claim, MADE TRUE.
//
// The claim was never checked: a shape that had stopped reaching its branch, or a
// branch with no shape at all, cost nothing. Two soft link-type branches had no shape
// at all. Both halves are pinned below.
//
// ROUND 2 made the soft half mean what it says. `problems.some((p) => !p.hard)` accepted
// ANY soft problem, and a `linkTypes` shape always raises a second, unrelated one (the
// per-project block is inert at the project layer) — so deleting BOTH soft link-type
// branches from `schema-config.mjs` left the BLZ-392 shape's own test green. Each soft
// shape now declares the message its own call site emits, and that is what is asserted.
// =============================================================================
describe("BLZ-414: every shape reaches its branch, and every soft link-type branch has a shape", () => {
  /** The problems one shape produces at EITHER layer — config-with-no-project, and
   *  project-with-no-config. A shape may be inert at one layer by design (a per-project
   *  `linkTypes` block is inert at the project layer; a top-level one is inert when it
   *  is the project's), so coverage is the union, not either half. */
  function problemsForShape(value) {
    const out = [];
    for (const [config, project] of [
      [buildConfig(value), buildProject(undefined)],
      [buildConfig(undefined), buildProject(value)],
    ]) {
      const topResolved = resolveSchema({ config });
      const endpointTypes = { ...topResolved.types, ...resolveSchema({ config, project }).types };
      out.push(...collectSchemaProblems({ ...topResolved, config, endpointTypes }));
      const resolved = { ...resolveSchema({ config, project }), linkTypes: topResolved.linkTypes };
      out.push(...collectSchemaProblems({ ...resolved, config, project, endpointTypes }));
    }
    return out;
  }

  for (const [name, value] of HARD_SHAPES) {
    test(`hard shape reaches a hard branch: ${name}`, () => {
      const problems = problemsForShape(value);
      assert.ok(problems.some((p) => p.hard),
        `the shape [${name}] produced no HARD problem at either layer — it no longer `
        + "exercises the call site the shape list says it stands for");
    });
  }

  for (const [name, value, branch] of SOFT_SHAPES) {
    test(`soft shape reaches ITS OWN soft branch and no hard one: ${name}`, () => {
      const problems = problemsForShape(value);
      // The shape's own branch, named — not "some soft problem happened". A `linkTypes`
      // shape always ALSO raises the inert-per-project-block problem at the project
      // layer, so the weaker form stayed green with both link-type branches deleted.
      assert.ok(branch instanceof RegExp,
        `the shape [${name}] declares no branch message — every soft shape must name the `
        + "call site it stands for, or this test is back to accepting any soft problem");
      assert.ok(problems.some((p) => !p.hard && branch.test(p.message)),
        `the shape [${name}] produced no soft problem matching ${branch} at either layer `
        + `— it no longer reaches the call site the shape list says it stands for. `
        + `Soft problems seen: ${JSON.stringify(problems.filter((p) => !p.hard).map((p) => p.message))}`);
      assert.deepEqual(problems.filter((p) => p.hard).map((p) => p.message), [],
        `the shape [${name}] is listed as SOFT but produced a hard problem`);
    });
  }

  for (const [name, value] of CONTROL_SHAPES) {
    test(`control shape produces nothing at all: ${name}`, () => {
      assert.deepEqual(problemsForShape(value).map((p) => p.message), [],
        `the control shape [${name}] produced a problem — it is no longer a control`);
    });
  }

  test("the undeclared-endpoint-kind soft branch is reached BY THE CROSS-PRODUCT", () => {
    // The first of the two link-type branches BLZ-414 found unexercised. It is
    // reachable through the config layering, so it is a shape in SOFT_SHAPES above and
    // this names the message the cross-product must therefore be producing.
    const problems = problemsForShape(
      { linkTypes: { Precedes: { source_kinds: ["ghost"], target_kinds: ["task"] } } });
    const hit = problems.filter((p) => !p.hard
      && /link type "Precedes" names "ghost" in source_kinds/.test(p.message));
    assert.ok(hit.length > 0,
      `the undeclared-endpoint-kind branch produced nothing: ${JSON.stringify(problems)}`);
  });

  test("the non-array-endpoint soft branch is UNREACHABLE through the config layering, and is pinned by a direct call", () => {
    // The second branch. Stated plainly rather than implied (work order section 3): NO
    // config-shaped override can reach it, because `mergeLinkTypes` drops an entry whose
    // `source_kinds`/`target_kinds` is not an array and keeps the shipped default, so
    // every array `resolveSchema` ever returns has array endpoints. It therefore cannot
    // be killed by any mutation driven through a config, and this file must not imply
    // that the cross-product pins it.
    for (const [, value] of SHAPES) {
      const resolved = resolveSchema({ config: buildConfig(value), project: buildProject(value) });
      for (const lt of resolved.linkTypes) {
        for (const side of ["source_kinds", "target_kinds"]) {
          assert.ok(Array.isArray(lt[side]),
            `resolveSchema returned a non-array ${side} — the unreachability claim above is `
            + "no longer true and this branch needs a cross-product shape after all");
        }
      }
    }
    // It IS reachable by a direct caller, which is what the branch's own comment says it
    // exists for ("validateSchema is a pure function anyone may call with anything"), so
    // it is pinned there: deleting the branch turns THIS test red.
    const problems = collectSchemaProblems({
      types: { task: { level: 0, workflow: "delivery", parentTypes: [], required: [] } },
      workflows: {},
      linkTypes: [{ name: "Precedes", source_kinds: "task", target_kinds: ["task"] }],
      config: {},
    });
    const hit = problems.filter((p) => !p.hard
      && /link type "Precedes" has a source_kinds that is not an array \(string\)/.test(p.message));
    assert.equal(hit.length, 1,
      `the non-array-endpoint branch produced nothing: ${JSON.stringify(problems)}`);
  });
});
