// tests/schema-audit-load-agreement-oracle.test.mjs — BLZ-407.
//
// THE PRODUCT ASSERTION: `blaze audit`'s `ok` and the load path's refusal agree, for every
// schema-override shape. Before this ticket they did not — a board whose `blaze.config.json`
// carried `{"schema": {"types": {"spike": 7}}}` made `blaze audit` report `ok=true` while
// every non-exempt verb refused with `SchemaOverrideError`, the SAME message, because
// `auditCorpus` read `validateSchema`'s flattened strings and filed every problem under one
// soft kind — the severity tag `collectSchemaProblems` already carries was thrown away.
//
// GROUND TRUTH IS `assertSchemaValid`, NOT THE AUDIT. Every case below runs the real load-path
// mechanism (mirroring `scripts/cli.mjs`'s preflight exactly: the top layer, then each project
// layer, refuse if either throws) and compares its actual throw/no-throw against `auditCorpus`'s
// actual `ok`. Neither side is derived from the other, and neither is computed from a hardcoded
// list of "these shapes are hard" — that is the vacuity trap a run of five wrong severities in a
// row on a sibling ticket fell into, each round pinning only the case that made its round's
// claim true.
//
// THE CROSS-PRODUCT is generated by nested loops over ONE list of override shapes, applied to
// BOTH layers (`blaze.config.json`'s `schema` and a `project.json`'s `schema`) — not a
// hand-written table of (config, project) pairs. The shape list itself is read off
// `collectSchemaProblems` (scripts/model/schema-config.mjs): one entry per `hard(...)` call
// site, one per `soft(...)` call site, and the well-formed controls.
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { auditCorpus } from "../scripts/model/audit.mjs";
import { resolveSchema, assertSchemaValid, validateSchema, collectSchemaProblems }
  from "../scripts/model/schema-config.mjs";

// --- the override shapes, one per branch of collectSchemaProblems ----------------------------
// Each entry is `[name, value]`, where `value` is what would sit at `schema` in either
// blaze.config.json or project.json. `undefined` means the block is absent — a layer's own
// well-formed control. A shape is applied identically at either layer; which branch it
// exercises where is NOT hand-predicted here (some are layer-specific, e.g. a per-project
// `linkTypes` block is inert only at the project layer) — the oracle asks the real functions,
// not this list, what a given placement produces.

// One custom type ("spike") and one custom workflow ("tiny") isolate every shape from the
// engine's own defaults, so a shape only ever changes what it names.
const HARD_SHAPES = [
  ["type: not an object", { types: { spike: 7 } }],
  ["type: bad level", { types: { spike: { level: "0", workflow: "delivery", parentTypes: [], required: [] } } }],
  ["type: workflow not a name", { types: { spike: { level: 0, workflow: 7, parentTypes: [], required: [] } } }],
  ["type: workflow names an undeclared workflow", { types: { spike: { level: 0, workflow: "ghost", parentTypes: [], required: [] } } }],
  ["type: parentTypes not an array", { types: { spike: { level: 0, workflow: "delivery", parentTypes: "x", required: [] } } }],
  ["type: parentTypes names an undeclared type", { types: { spike: { level: 0, workflow: "delivery", parentTypes: ["nope"], required: [] } } }],
  ["type: required not an array", { types: { spike: { level: 0, workflow: "delivery", parentTypes: [], required: "x" } } }],
  ["type: required entry not a field name", { types: { spike: { level: 0, workflow: "delivery", parentTypes: [], required: ["title", 3] } } }],
  ["workflow: not an object", { workflows: { tiny: 7 } }],
  ["workflow: statuses not a non-empty array", { workflows: { tiny: { statuses: [], terminal: [], transitions: [], resolutionOnTerminal: {} } } }],
  ["workflow: missing terminal", { workflows: { tiny: { statuses: ["a", "b"], transitions: [["a", "b"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: terminal not an array", { workflows: { tiny: { statuses: ["a", "b"], terminal: "b", transitions: [["a", "b"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a terminal not among its statuses", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["c"], transitions: [["a", "b"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: missing transitions", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: transitions not an array", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: "x", resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a transition not a [from,to] pair", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a transition names an unknown status", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "c"]], resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: a bad reopenTo", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], reopenTo: "c", resolutionOnTerminal: { b: "done" } } } }],
  ["workflow: missing resolutionOnTerminal", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]] } } }],
  ["workflow: resolutionOnTerminal not an object", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], resolutionOnTerminal: "x" } } }],
  ["workflow: a resolution on an unknown status", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], resolutionOnTerminal: { a: "done" } } } }],
  ["workflow: a non-resolution value", { workflows: { tiny: { statuses: ["a", "b"], terminal: ["b"], transitions: [["a", "b"]], resolutionOnTerminal: { b: "bogus" } } } }],
  ["types container is the wrong shape (BLZ-396)", { types: "notanobject" }],
  ["workflows container is the wrong shape (BLZ-396)", { workflows: 42 }],
  ["whole schema is a string", "a string"],
  ["whole schema is an array", ["x"]],
];

const SOFT_SHAPES = [
  ["an inert per-project linkTypes block", { linkTypes: { Precedes: { source_kinds: ["task"], target_kinds: ["task"] } } }],
  ["a malformed top-level schema.linkTypes entry", { linkTypes: { Precedes: { source_kinds: "nope", target_kinds: [] } } }],
  ["a deliberately narrowed requirement workflow (BLZ-361)", { workflows: { requirement: {
    statuses: ["proposed", "implemented", "rejected", "obsolete"],
    terminal: ["implemented", "rejected", "obsolete"],
    transitions: [["proposed", "implemented"], ["proposed", "rejected"], ["proposed", "obsolete"],
                  ["implemented", "obsolete"]],
    reopenTo: "proposed",
    resolutionOnTerminal: { implemented: "done", rejected: "wont-do", obsolete: "wont-do" },
  } } }],
];

const CONTROL_SHAPES = [
  ["absent — no schema block at all", undefined],
  ["well-formed custom type", { types: { spike: { level: 0, workflow: "delivery", parentTypes: [], required: [] } } }],
];

const SHAPES = [...HARD_SHAPES, ...SOFT_SHAPES, ...CONTROL_SHAPES];

// --- ground truth and the mechanism under test ------------------------------------------------

const buildConfig = (v) => (v === undefined ? {} : { schema: v });
const buildProject = (v) => (v === undefined ? { key: "P" } : { key: "P", schema: v });

/** Mirrors scripts/cli.mjs's preflight EXACTLY: the top layer, then each project layer, and
 *  refuse the moment either throws. This — NOT a prediction — is ground truth. */
function loadPathRefuses(config, project) {
  const top = resolveSchema({ config });
  try { assertSchemaValid({ ...top, config }); }
  catch { return true; }
  const resolved = { ...resolveSchema({ config, project }), linkTypes: top.linkTypes };
  try { assertSchemaValid({ ...resolved, config, project }); }
  catch { return true; }
  return false;
}

/** What `auditCorpus` SHOULD produce for the schema layer, computed independently of it: the
 *  same top-then-project walk with cross-layer dedup by message, but built here from
 *  `collectSchemaProblems` directly rather than by calling `auditCorpus` and trusting its own
 *  bookkeeping. Returns the hard/soft partition of every DISTINCT message. */
function expectedPartition(config, project) {
  const topResolved = resolveSchema({ config });
  const endpointTypes = { ...topResolved.types, ...resolveSchema({ config, project }).types };
  const topProblems = collectSchemaProblems({ ...topResolved, config, endpointTypes });
  const topByMsg = new Map();
  for (const p of topProblems) if (!topByMsg.has(p.message)) topByMsg.set(p.message, p.hard);
  const resolved = { ...resolveSchema({ config, project }), linkTypes: topResolved.linkTypes };
  const projProblems = collectSchemaProblems({ ...resolved, config, project, endpointTypes })
    .filter((p) => !topByMsg.has(p.message));
  const hard = new Set(), soft = new Set();
  for (const [msg, isHard] of topByMsg) (isHard ? hard : soft).add(msg);
  for (const p of projProblems) (p.hard ? hard : soft).add(p.message);
  return { hard, soft };
}

/** The union `validateSchema` itself would report for the same two layers, deduped the same
 *  way — the independent reference for "no problem lost or duplicated" (validateSchema is the
 *  long-established, separately-tested reporting path; this does not call collectSchemaProblems
 *  at all). */
function expectedDetailSetViaValidateSchema(config, project) {
  const topResolved = resolveSchema({ config });
  const endpointTypes = { ...topResolved.types, ...resolveSchema({ config, project }).types };
  const topMsgs = validateSchema({ ...topResolved, config, endpointTypes });
  const topSet = new Set(topMsgs);
  const resolved = { ...resolveSchema({ config, project }), linkTypes: topResolved.linkTypes };
  const projMsgs = validateSchema({ ...resolved, config, project, endpointTypes })
    .filter((m) => !topSet.has(m));
  return new Set([...topSet, ...projMsgs]);
}

const oneGoalTicket = { frontmatter: { id: "P-1", type: "goal", components: [], labels: [], links: [] }, body: "x" };

const sorted = (s) => [...s].sort();

describe("BLZ-407 oracle: blaze audit's ok agrees with the load path's refusal, for every schema-override shape", () => {
  let cases = 0;
  let clauses = 0;
  const check = (cond, msg) => { clauses++; assert.ok(cond, msg); };
  const sameSet = (actual, expected, msg) => { clauses++; assert.deepEqual(sorted(actual), sorted(expected), msg); };

  for (const [configName, configValue] of SHAPES) {
    for (const [projectName, projectValue] of SHAPES) {
      cases++;
      test(`config=[${configName}] x project=[${projectName}]`, () => {
        const config = buildConfig(configValue);
        const project = buildProject(projectValue);

        const refused = loadPathRefuses(config, project);
        const audit = auditCorpus({ tickets: [oneGoalTicket], projects: { P: project }, config });

        // --- the ok/refusal agreement, both directions ----------------------------------
        check(!(refused && audit.ok),
          `assertSchemaValid throws for config=[${configName}] project=[${projectName}] `
          + `but audit.ok is still true`);
        check(!(!refused && !audit.ok),
          `assertSchemaValid does not throw for config=[${configName}] project=[${projectName}] `
          + `but audit.ok is false — the mirror-image over-refusal`);

        // --- the finding-level claim: no problem lost, duplicated, or under the wrong kind ---
        const actualHard = new Set(audit.findings
          .filter((f) => f.kind === "schema-malformed").map((f) => f.detail));
        const actualSoft = new Set(audit.findings
          .filter((f) => f.kind === "schema-invalid").map((f) => f.detail));
        const expected = expectedPartition(config, project);
        sameSet(actualHard, expected.hard,
          `schema-malformed details differ from collectSchemaProblems's hard partition `
          + `for config=[${configName}] project=[${projectName}]`);
        sameSet(actualSoft, expected.soft,
          `schema-invalid details differ from collectSchemaProblems's soft partition `
          + `for config=[${configName}] project=[${projectName}]`);
        check([...actualHard].every((m) => !actualSoft.has(m)),
          `a message is filed under BOTH schema-malformed and schema-invalid for `
          + `config=[${configName}] project=[${projectName}]`);

        // --- the union equals validateSchema's own output, as a set (independent reference) ---
        const union = new Set([...actualHard, ...actualSoft]);
        sameSet(union, expectedDetailSetViaValidateSchema(config, project),
          `schema-malformed ∪ schema-invalid details differ from validateSchema's output `
          + `for config=[${configName}] project=[${projectName}]`);
      });
    }
  }

  test("the oracle's own scale — reported so it cannot silently shrink", () => {
    const expectedCases = SHAPES.length * SHAPES.length;
    assert.equal(cases, expectedCases,
      `expected ${SHAPES.length} shapes squared; the loop above enumerated something else`);
    // 6 clauses per case: 2 ok-agreement directions, 2 partition-set comparisons, 1
    // no-overlap check, 1 union-vs-validateSchema comparison. Printed rather than only
    // asserted, so a run's real count reaches the PR body verbatim.
    console.log(`BLZ-407 oracle: ${cases} cases (${SHAPES.length} shapes squared), `
      + `${clauses} clauses checked so far this run`);
  });
});
